name: Build check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          touch .env
          echo MICROCMS_SERVICE_DOMAIN=${{ secrets.MICROCMS_SERVICE_DOMAIN }} >> .env
          echo MICROCMS_SERVICE_DOMAIN=${{ secrets.MICROCMS_API_KEY }} >> .env
      - name: Build
        run: |
          npm install
          npm run build
